inherit_from: 'https://raw.githubusercontent.com/PublicHealthEngland/ndr_dev_support/master/.rubocop.yml'

AllCops:
  Exclude:
    - test/dummy/db/schema.rb
  TargetRubyVersion: 2.6 # minimum we support
